//user types
export const GET_AUTHENTICATED_USER = "GET_AUTHENTICATED_USER";
export const SET_LOADING_USER = "SET_LOADING_USER";
export const STOP_LOADING_USER = "STOP_LOADING_USER";

//data types
export const GET_ORIENTATION_OVERVIEW = "GET_ORIENTATION_OVERVIEW";
export const GET_ORIENTATION_PAGES = "GET_ORIENTATION_PAGES";
export const GET_ORIENTATION_PAGE = "GET_ORIENTATION_PAGE";
export const GET_USER_COLLEGE = "GET_USER_COLLEGE";
export const GET_USER_CAMPUS = "GET_USER_CAMPUS";
export const SET_LOADING_DATA = "SET_LOADING_DATA";
export const STOP_LOADING_DATA = "STOP_LOADING_DATA";

//ui types
