//user types
export const GET_AUTHENTICATED_USER = "GET_AUTHENTICATED_USER";
export const SET_LOADING_USER = "SET_LOADING_USER";
export const STOP_LOADING_USER = "STOP_LOADING_USER";
export const ADD_USER_CLUB = "ADD_USER_CLUB";

//data types
//orientation
export const GET_ORIENTATION_OVERVIEW = "GET_ORIENTATION_OVERVIEW";
export const GET_ORIENTATION_PAGES = "GET_ORIENTATION_PAGES";
export const GET_ORIENTATION_PAGE = "GET_ORIENTATION_PAGE";
export const GET_USER_COLLEGE = "GET_USER_COLLEGE";
export const GET_USER_CAMPUS = "GET_USER_CAMPUS";
export const SET_LOADING_DATA = "SET_LOADING_DATA";
export const STOP_LOADING_DATA = "STOP_LOADING_DATA";
//club
export const GET_A_CLUB_DATA = "GET_A_CLUB_DATA";
export const RESET_CLUB_DATA = "RESET_CLUB_DATA";
export const SET_CLUB_MEMBERS_DATA = "SET_CLUB_MEMBERS_DATA";
export const SET_CLUB_CURRENT_MEMBER_DATA = "SET_CLUB_CURRENT_MEMBER_DATA";
export const UPDATE_CLUB_MEMBER_BIO = "UPDATE_CLUB_MEMBER_BIO";
export const UPDATE_CLUB_MEMBER_PHOTO = "UPDATE_CLUB_MEMBER_PHOTO";

//ui types
