//user types
export const GET_AUTHENTICATED_USER = "GET_AUTHENTICATED_USER";
export const SET_LOADING_USER = "SET_LOADING_USER";
export const STOP_LOADING_USER = "STOP_LOADING_USER";
export const ADD_USER_CLUB = "ADD_USER_CLUB";
export const LOGOUT = "LOGOUT";
export const UPDATE_USER_PHOTO = "UPDATE_USER_PHOTO";
export const UPDATE_USER_BIO = "UPDATE_USER_BIO";
export const SET_NOTIFICATION_AVAILABLE = "SET_NOTIFICATION_AVAILABLE";

//data types
//orientation
export const GET_ORIENTATION_OVERVIEW = "GET_ORIENTATION_OVERVIEW";
export const GET_ORIENTATION_PAGES = "GET_ORIENTATION_PAGES";
export const GET_ORIENTATION_PAGE = "GET_ORIENTATION_PAGE";
export const RESET_ORIENTATION_PAGE = "RESET_ORIENTATION_PAGE";
export const GET_USER_COLLEGE = "GET_USER_COLLEGE";
export const GET_USER_CAMPUS = "GET_USER_CAMPUS";
export const SET_LOADING_DATA = "SET_LOADING_DATA";
export const STOP_LOADING_DATA = "STOP_LOADING_DATA";
//club
export const GET_A_CLUB_DATA = "GET_A_CLUB_DATA";
export const RESET_CLUB_DATA = "RESET_CLUB_DATA";
export const SET_CLUB_MEMBERS_DATA = "SET_CLUB_MEMBERS_DATA";
export const SET_CLUB_CURRENT_MEMBER_DATA = "SET_CLUB_CURRENT_MEMBER_DATA";
export const UPDATE_CLUB_MEMBER_BIO = "UPDATE_CLUB_MEMBER_BIO";
export const UPDATE_CLUB_MEMBER_PHOTO = "UPDATE_CLUB_MEMBER_PHOTO";
export const SET_CLUB_GALLERY = "SET_CLUB_GALLERY";
export const ADD_CLUB_GALLERY = "ADD_CLUB_GALLERY";
export const DELETE_GALLERY = "DELETE_GALLERY";
export const SET_CLUB_GALLERY_TO_TRUE = "SET_CLUB_GALLERY_TO_TRUE";
export const SET_CLUB_GALLERY_TO_FALSE = "SET_CLUB_GALLERY_TO_FALSE";
export const SET_CLUB_EVENT = "SET_CLUB_EVENT";
export const ADD_CLUB_EVENT = "ADD_CLUB_EVENT";
export const DELETE_EVENT = "DELETE_EVENT";
export const SET_CLUB_EVENT_TO_TRUE = "SET_CLUB_EVENT_TO_TRUE";
export const SET_CLUB_EVENT_TO_FALSE = "SET_CLUB_EVENT_TO_FALSE";
export const UPDATE_CLUB_DETAILS = "UPDATE_CLUB_DETAILS";
export const ACTIVATE_CLUB = "ACTIVATE_CLUB";
export const DEACTIVATE_CLUB = "DEACTIVATE_CLUB";
export const JOIN_CLUB = "JOIN_CLUB";
export const ACCEPT_NEW_CLUB_MEMBER = "ACCEPT_NEW_CLUB_MEMBER";
export const REJECT_NEW_CLUB_MEMBER = "REJECT_NEW_CLUB_MEMBER";
export const ASSIGN_NEW_CLUB_ROLE = "ASSIGN_NEW_CLUB_ROLE";
export const ADD_NEW_CLUB_ROLE = "ADD_NEW_CLUB_ROLE";
export const DELETE_CLUB_ROLE = "DELETE_CLUB_ROLE";
export const DEACTIVATE_CLUB_MEMBER = "DEACTIVATE_CLUB_MEMBER";
export const UPDATE_CLUB_IMAGE = "UPDATE_CLUB_IMAGE";

//ui types
export const SET_UI_LOADING = "SET_UI_LOADING";
export const STOP_UI_LOADING = "STOP_UI_LOADING";
